### ISSUE TITLE
Support step configuration override

### ISSUE THREAD

**Issue by Dan-Bai** [Optum/runiac#25]
Following the readme to set up runiac.yaml with **execute_when** does not work.
If this var check can support regexp pattern matching as well that would be beneficial.

**Comment by tiny-dancer** [comment]
Thank you for the call out. The README docs are slightly out of date and will be trimmed down dramatically in favor of the content on runiac.io.

The execute_when config feature was not brought into the initial oss release. Do you mind sharing your use case to best understand how to bring the feature back?

**Comment by Dan-Bai** [comment]
I'm attempting to dynamically run specific steps depending on which variables are available. This is for building out a self service to provision Azure resources from configuration files. The top level (step1 and track) will depend on variables passed in from the configuration files while later steps will run if variables from previous steps and passed in exist.

**Comment by tiny-dancer** [comment]
Sounds like an awesome and advanced use case! I'd love to dig in a little deeper.  I'm on vaca this week, would you be free to connect via voice next week? I think we can get a feature lined up and delivered by the following week.

**Comment by tiny-dancer** [comment]
> This is for building out a self service to provision Azure resources from configuration files.

hey @Dan-Bai, do you mind expanding on this a bit to appreciate the full picture?  Being able to dynamically run steps based on contextual information (variables) is a powerful feature however quite complex (the reason it was excluded from the oss release).  Curious to thought experiment alternative solutions that may either solve the use case or better define the new feature.

**Comment by tiny-dancer** [comment]
hey @Dan-Bai after connecting offline - is this issue still relevant as is or was the technical problem solved in another way?

Thanks!

**Comment by Dan-Bai** [comment]
I was able to work around the problem. Thank you for the advise!
