### ISSUE TITLE
Azure CLI version is old within `runiac deploy...`

### ISSUE THREAD

**Issue by rjseibert** [Optum/runiac#45]
The azure cli version is old during a `runiac deploy...`.  Azure cli is on version `2.13.0`.  Python is on version `Python (Linux) 3.8.10 (default, May  6 2021, 00:05:59) `.

Within the runiac image, I am getting: 

(```
deploy default/az_front_door/primary/centralus)   CLIInternalError: The command failed with an unexpected error. Here is the traceback:
(deploy default/az_front_door/primary/centralus)   cannot import name 'ArgumentUsageError' from 'azure.cli.core.azclierror' (/usr/lib/python3.8/site-packages/azure/cli/core/azclierror.py)
(deploy default/az_front_door/primary/centralus)   Traceback (most recent call last):
(deploy default/az_front_door/primary/centralus)     File "/usr/lib/python3.8/site-packages/knack/cli.py", line 215, in invoke
(deploy default/az_front_door/primary/centralus)       cmd_result = self.invocation.execute(args)
(deploy default/az_front_door/primary/centralus)     File "/usr/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 654, in execute
(deploy default/az_front_door/primary/centralus)       raise ex
(deploy default/az_front_door/primary/centralus)     File "/usr/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_jobs_serially
(deploy default/az_front_door/primary/centralus)       results.append(self._run_job(expanded_arg, cmd_copy))
(deploy default/az_front_door/primary/centralus)     File "/usr/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 711, in _run_job
(deploy default/az_front_door/primary/centralus)       six.reraise(*sys.exc_info())
(deploy default/az_front_door/primary/centralus)     File "/usr/lib/python3.8/site-packages/six.py", line 703, in reraise
(deploy default/az_front_door/primary/centralus)       raise value
(deploy default/az_front_door/primary/centralus)     File "/usr/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 688, in _run_job
(deploy default/az_front_door/primary/centralus)       result = cmd_copy(params)
(deploy default/az_front_door/primary/centralus)     File "/usr/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 325, in __call__
(deploy default/az_front_door/primary/centralus)       return self.handler(*args, **kwargs)
(deploy default/az_front_door/primary/centralus)     File "/usr/lib/python3.8/site-packages/azure/cli/core/__init__.py", line 784, in default_command_handler
(deploy default/az_front_door/primary/centralus)       return op(**command_args)
(deploy default/az_front_door/primary/centralus)     File "/root/.azure/cliextensions/front-door/azext_front_door/custom.py", line 343, in configure_fd_frontend_endpoint_enable_https
(deploy default/az_front_door/primary/centralus)       from azure.cli.core.azclierror import ArgumentUsageError
(deploy default/az_front_door/primary/centralus)   ImportError: cannot import name 'ArgumentUsageError' from 'azure.cli.core.azclierror' (/usr/lib/python3.8/site-packages/azure/cli/core/azclierror.py)
(deploy default/az_front_door/primary/centralus)   To open an issue, please run: 'az feedback'

```

**Comment by tiny-dancer** [comment]
If looking to update the azure cli version in the provided runiac containers this can be done here: https://github.com/runiac/docker/blob/main/package/alpine-azure/Dockerfile#L8.   Otherwise if using a custom dockerfile this can be updated there as expected in your configurations

**Comment by rjseibert** [comment]
Honestly, I have no idea what you are trying to get me to do @tiny-dancer. I believe I am still using `runiac/deploy:latest-alpine-full` which seems to also be using the same version as the `alpine-azure` image (https://github.com/runiac/docker/blob/main/package/alpine-full/Dockerfile#L8).  Locally it still has `az version` as 2.13.

**Comment by tiny-dancer** [comment]
I see the builds are failing when doing our dockerhub pushes so it makes sense things are out of sync. Will be investigating.

**Comment by mkrouse** [comment]
This should be resolved now - the new version (`0.0.11`) has been pushed out.
