### ISSUE TITLE
How to manage Terraform Drift in Runiac

### ISSUE THREAD

**Issue by suraj5789** [Optum/runiac#47]
Hi all Contributor,

Thanks for creating such a nice tool :).  Well, it's not a issue. I want to know How Runiac manages the drift in Terraform resources like below reference link.

https://learn.hashicorp.com/tutorials/terraform/resource-drift?in=terraform/state

Any document/example would help.

Thanks in advance.

**Comment by tiny-dancer** [comment]
Hey @suraj5789, thanks for reaching out. 

The tl/dr answer is runiac will run terraform plan with a refresh parameter so out of the box any runiac deploy would attempt to resolve any configuration drift identified by terraform in the apply.  If any issues encounter with resolving the configuration drift, manual actions would need to be taken in the form of a) modifying statefile or b) ad-hoc resolution of the drift until terraform can cleanly execute.

Is there something additional you were hoping to see?


sorry for the delayed response, you caught me on disconnected time off.

**Comment by suraj5789** [comment]
Thanks @tiny-dancer for your answer, I will try with refresh parameter.

One small question for adding externally created resources, we use terraform import command like below
`terraform import aws_security_group.sg_web $SG_ID`

Do we have any provision under runiac or I should use terraform import command only to perform the task.

**Comment by tiny-dancer** [comment]
> Do we have any provision under runiac or I should use terraform import command only to perform the task?

No, this is a good call out.  It's been discussed to have the ability to quickly running ad-hoc terraform commands within the correct runiac context of steps to ease bouncing in and out of terraform and runiac.  TL/DR nothing implemented yet and we've seen most teams write a re-usable script around the boilerplate terraform commands

**Comment by suraj5789** [comment]
Thanks @tiny-dancer.
