### ISSUE TITLE
New Project - stream terminated PROTOCOL_ERROR

### ISSUE THREAD

**Issue by rjseibert** [Optum/runiac#48]
I am running:

`runiac deploy -a ${myAzureSubscription} -e stg --local --interactive -c ${name}`

I get the following error, along with a Dockerfile printed to std out.

```
#1 ERROR: rpc error: code = Internal desc = stream terminated by RST_STREAM with error code: PROTOCOL_ERROR
------
 > [internal] load build definition from entrypoint.sh"]
:
------
failed to solve with frontend dockerfile.v0: failed to read dockerfile: rpc error: code = Internal desc = stream terminated by RST_STREAM with error code: PROTOCOL_ERROR
```

The result of `runiac version`:

`runiac 0.0.10. Commit 09105498d06af7635168ffea7c61d4313918975f.  Built on 2021-10-18T23:50:56Z.`

I am starting a new repository and have included a new `runiac.yml`, Dockerfile from the template, and standard `entrypoint.sh`.

**Comment by mkrouse** [comment]
@rjseibert - this is currently a bug in version 10 of runiac which has been addressed but unfortunately our build pipelines are still failing to push out a new version (currently investigating).

Could you try adding this to your `runiac.yml` file and try again? This should fix this issue.

`dockerfile: .runiac/Dockerfile`

**Comment by rjseibert** [comment]
@mkrouse, thank you for the response.  This did indeed resolve my issue.  `runiac deploy` seems to only work when there is your experimental Dockerfile in both ./Dockerfile and ./.runiac/Dockerfile.  From a project structure perspective I have no idea where I should be putting "my" Dockerfile with the container that I want to deploy to public cloud environments.  I suppose the answer is perhaps to define a ./docker directory and put stuff there.

**Comment by mkrouse** [comment]
@rjseibert, Great!

> From a project structure perspective I have no idea where I should be putting "my" Dockerfile with the container that I want to deploy to public cloud environments.

I actually haven't done this before until now.  The  `-f ` flag is working for me with any name for the `dockerfile` at the root of the project on version `0.0.10` of runiac.

**Comment by rjseibert** [comment]
Speaking of that, it would be helpful if there were something on how to use these flags. I get the following message from `runiac -h`.  I didn't know the `-f` flag existed, and probably have no way to discover that it exists.

```
A friendly, portable infrastructure as code runner built with
love by tiny-dancer and friends. Open sourced for the community by Optum.
Complete documentation is available at https://runiac.io

Usage:
  runiac [flags]
  runiac [command]

Available Commands:
  deploy      Deploy configurations
  help        Help about any command
  new         Create a new runiac project
  version     Print the version number of runiac

Flags:
  -h, --help   help for runiac

Use "runiac [command] --help" for more information about a command.
```

**Comment by mkrouse** [comment]
try `runiac deploy -h` :)
